import fs from 'fs';
import path from 'path';
import { DatabaseSchema } from '../src/types';

const DB_FILE_PATH = path.join(process.cwd(), 'server', 'data.json');

const INITIAL_DATABASE: DatabaseSchema = {
  hero: {
    title: 'ZOHA 2.0',
    subtitle: 'MUSIC • STORIES • VISUALS',
    taglines: 'Where melody meets cinematic dimension',
    description: 'Welcome to my world. An intimate realm of acoustic resonance, electric dreams, visual poetry, and live soundscapes.',
    portraitUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1920&q=85',
    ctaPrimaryText: 'LISTEN NOW',
    ctaPrimaryLink: '#music',
    ctaSecondaryText: 'WATCH VIDEOS',
    ctaSecondaryLink: '#videos',
    ctaTertiaryText: 'ENTER MY WORLD',
    ctaTertiaryLink: '#universe',
    overlayStrength: 0.65,
    alignment: 'center',
  },
  about: {
    name: 'ZOHA',
    artistTitle: 'Singer • Musician • Guitarist • Visual Artist',
    shortBio: 'Exploring the intersection of raw acoustic strings, atmospheric vocals, and cinematic storytelling.',
    creativePhilosophy: 'Music is not merely sound—it is the architecture of memory and emotional light.',
    portraitUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=85',
    signatureText: 'Zoha',
    stats: {
      songs: '18+',
      videos: '32+',
      photos: '120+',
      performances: '45+',
      projects: '12+',
    },
    story: 'From humble acoustic fingerpicking in late-night bedroom sessions to electrifying live festival stages, my journey has always been guided by a singular obsession: creating music that transports the listener into another dimension.',
    musicPhilosophy: 'Every chord carries a narrative. When acoustic guitars blend with modern synth textures and evocative vocals, ordinary moments transform into cinematic journeys.',
    inspiration: 'Inspired by nighttime cityscapes, timeless film scores, vintage analog guitars, and the quiet resonance of raw human emotions.',
    instruments: ['Fender Stratocaster', 'Taylor Acoustic 814ce', 'Vintage Gibson Les Paul', 'Moog Sub 37', 'Grand Piano'],
    dreams: 'To orchestrate world-class immersive audio-visual arena experiences that unite millions across the globe through music.',
  },
  songs: [
    {
      id: 'song-1',
      title: 'Midnight Resonance',
      artist: 'ZOHA',
      genre: 'Cinematic Acoustic',
      releaseDate: '2026-02-14',
      duration: '3:45',
      audioUrl: 'https://cdn.freesound.org/previews/612/612610_5674468-lq.mp3',
      coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
      description: 'A delicate tapestry of fingerstyle acoustic guitar over swelling twilight pads and emotive vocal lines.',
      lyrics: 'Under the sapphire glow / We let the river flow / Midnight resonance in my soul...',
      featured: true,
      published: true,
      plays: 14200,
      order: 1,
    },
    {
      id: 'song-2',
      title: 'Starlight Echoes',
      artist: 'ZOHA',
      genre: 'Indie Dream Pop',
      releaseDate: '2025-11-20',
      duration: '4:12',
      audioUrl: 'https://cdn.freesound.org/previews/618/618210_11861866-lq.mp3',
      coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
      description: 'Driving rhythmic percussion paired with soaring reverberant guitar melodies recorded during a late autumn night.',
      lyrics: 'Echoes in the dark / Igniting every spark / Far beyond the stars...',
      featured: false,
      published: true,
      plays: 9840,
      order: 2,
    },
    {
      id: 'song-3',
      title: 'Neon Odyssey',
      artist: 'ZOHA',
      genre: 'Synthwave & Electric Guitar',
      releaseDate: '2025-08-05',
      duration: '3:28',
      audioUrl: 'https://cdn.freesound.org/previews/563/563810_11861866-lq.mp3',
      coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80',
      description: 'An adrenaline-fueled fusion of 80s analog synthesizers and a scorching guitar solo climax.',
      lyrics: 'Through the neon rain / Breaking every chain / Nothing stays the same...',
      featured: false,
      published: true,
      plays: 18920,
      order: 3,
    },
    {
      id: 'song-4',
      title: 'Acoustic Horizon (Live)',
      artist: 'ZOHA',
      genre: 'Live Acoustic',
      releaseDate: '2025-04-18',
      duration: '5:02',
      audioUrl: 'https://cdn.freesound.org/previews/573/573381_11861866-lq.mp3',
      coverUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80',
      description: 'Captured live in intimate studio session with just a 12-string guitar and a single vintage tube mic.',
      lyrics: 'Horizon calls my name / The fire in the frame...',
      featured: false,
      published: true,
      plays: 7650,
      order: 4,
    },
  ],
  videos: [
    {
      id: 'vid-1',
      title: 'Midnight Resonance - Official Visualizer & Acoustic Performance',
      youtubeUrl: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
      videoId: 'kJQP7kiw5Fk',
      category: 'MUSIC',
      thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
      description: 'Official visual experience capturing live acoustic performance in a cinematic dark studio.',
      featured: true,
      published: true,
      duration: '3:50',
      views: 34200,
      order: 1,
    },
    {
      id: 'vid-2',
      title: 'Fingerstyle Guitar Cover - Cinematic Acoustic Session',
      youtubeUrl: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ',
      videoId: 'fJ9rUzIMcZQ',
      category: 'COVER',
      thumbnail: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=800&q=80',
      description: 'Reimagining a timeless classic on my custom Taylor 814ce acoustic with percussive harmonics.',
      featured: false,
      published: true,
      duration: '4:15',
      views: 28900,
      order: 2,
    },
    {
      id: 'vid-3',
      title: 'Live at Aurora Hall 2025 - Full Electric Guitar Solo',
      youtubeUrl: 'https://www.youtube.com/watch?v=9bZkp7q19f0',
      videoId: '9bZkp7q19f0',
      category: 'LIVE',
      thumbnail: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
      description: 'Live performance from our headline show at Aurora Hall with immersive light show.',
      featured: false,
      published: true,
      duration: '6:30',
      views: 45100,
      order: 3,
    },
    {
      id: 'vid-4',
      title: 'Building ZOHA 2.0 Studio - Behind The Scenes Vlog',
      youtubeUrl: 'https://www.youtube.com/watch?v=CevxZvSJLk8',
      videoId: 'CevxZvSJLk8',
      category: 'BEHIND THE SCENES',
      thumbnail: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80',
      description: 'A walkthrough of my sound design workstation, guitar pedals, and recording chain.',
      featured: false,
      published: true,
      duration: '11:20',
      views: 19400,
      order: 4,
    },
  ],
  gallery: [
    {
      id: 'gal-1',
      title: 'The Electric Silhouette',
      description: 'Captured under moody violet arena lights during the 2025 Summer Tour.',
      category: 'Performances',
      imageUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=85',
      featured: true,
      published: true,
      likes: 540,
      order: 1,
    },
    {
      id: 'gal-2',
      title: 'Acoustic Solitude',
      description: 'Late night composition session with my custom handcrafted mahogany acoustic.',
      category: 'Studio',
      imageUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=1200&q=85',
      featured: true,
      published: true,
      likes: 420,
      order: 2,
    },
    {
      id: 'gal-3',
      title: 'Golden Hour Reflections',
      description: 'Editorial portrait shoot overlooking the Pacific coastline.',
      category: 'Portraits',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85',
      featured: false,
      published: true,
      likes: 680,
      order: 3,
    },
    {
      id: 'gal-4',
      title: 'Analog Pedals & Warm Tubes',
      description: 'Dialing in the signature saturated chorus tone for Midnight Resonance.',
      category: 'Studio',
      imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=85',
      featured: false,
      published: true,
      likes: 310,
      order: 4,
    },
    {
      id: 'gal-5',
      title: 'Neon Echoes Arena',
      description: 'The moment the drop hit and 5,000 flashlights lit up the stadium.',
      category: 'Performances',
      imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=85',
      featured: true,
      published: true,
      likes: 890,
      order: 5,
    },
    {
      id: 'gal-6',
      title: 'Tokyo Rain & Soundscapes',
      description: 'Capturing field recordings of rain on neon umbrellas for album textures.',
      category: 'Travel',
      imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=85',
      featured: false,
      published: true,
      likes: 475,
      order: 6,
    },
  ],
  stories: [
    {
      id: 'story-1',
      title: 'The Night I First Played Live',
      date: 'October 14, 2024',
      excerpt: 'Hands trembling, a dimly lit basement venue, and six steel strings that changed my entire life.',
      content: `I will never forget the smell of that basement venue—a mix of old amplifier tubes, rain-soaked asphalt outside, and pure anticipation. 

When the stage lights flickered on, my fingers felt completely numb. But the moment I struck that first open D-minor chord on my acoustic, the nervous static dissolved into absolute focus. The entire room went dead silent.

By the time the final chorus peaked, the crowd was singing every single harmony with their eyes closed. That was the night I understood that music isn't about perfection; it's about courage and visceral human connection.`,
      coverImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=85',
      youtubeUrl: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
      audioTrackId: 'song-1',
      published: true,
      readTime: '4 min read',
    },
    {
      id: 'story-2',
      title: 'Writing Midnight Resonance in a Storm',
      date: 'January 22, 2025',
      excerpt: 'How a winter blackout in the mountains inspired an entire acoustic soundscape.',
      content: `A sudden blizzard took down the power grid for nearly 36 hours. With no screens, no internet, and only the crackling fireplace for light, I grabbed my acoustic guitar and let the storm dictate the rhythm.

The rain tapping against the tin roof became the rhythmic pulse. The howling wind outside shaped the sweeping vocal melodies. By sunrise, Midnight Resonance had taken its complete shape in one continuous stream of consciousness.`,
      coverImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=85',
      youtubeUrl: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ',
      audioTrackId: 'song-1',
      published: true,
      readTime: '3 min read',
    },
  ],
  journey: [
    {
      id: 'jour-1',
      year: '2023',
      date: 'Spring 2023',
      title: 'First Acoustic Recordings',
      description: 'Began recording intimate acoustic guitar arrangements and uploading late-night demos to YouTube.',
      category: 'Origin',
      imageUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=800&q=80',
      published: true,
      order: 1,
    },
    {
      id: 'jour-2',
      year: '2024',
      date: 'Autumn 2024',
      title: 'First Major Live Performance',
      description: 'Headlined an unforgettable sold-out indie music night at The Soundhouse, connecting with thousands of listeners.',
      category: 'Performance',
      imageUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=800&q=80',
      published: true,
      order: 2,
    },
    {
      id: 'jour-3',
      year: '2025',
      date: 'Summer 2025',
      title: 'Studio Expansion & Hybrid Synthesis',
      description: 'Integrated vintage analog synthesizers with acoustic fingerstyle arrangements, forging the signature ZOHA sound.',
      category: 'Innovation',
      imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80',
      published: true,
      order: 3,
    },
    {
      id: 'jour-4',
      year: '2026',
      date: 'Present & Beyond',
      title: 'ZOHA 2.0 Official Global Platform',
      description: 'Launching the full cinematic interactive ecosystem, immersive releases, world tour dates, and visual exhibitions.',
      category: 'Milestone',
      imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
      published: true,
      order: 4,
    },
  ],
  events: [
    {
      id: 'ev-1',
      title: 'ZOHA 2.0 Live: The Midnight Resonance Tour',
      date: '2026-10-15',
      time: '20:00',
      location: 'Los Angeles, CA',
      venue: 'The Wiltern Theatre',
      description: 'An exclusive audiovisual concert featuring immersive 360-degree acoustics, live string quartet, and visual projections.',
      ticketUrl: 'https://tickets.example.com/zoha-la',
      status: 'UPCOMING',
      published: true,
      image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'ev-2',
      title: 'Acoustic Intimates: Unplugged Session',
      date: '2026-11-04',
      time: '19:30',
      location: 'New York, NY',
      venue: 'Brooklyn Art Cave',
      description: 'Limited 150-seat acoustic storytelling and Q&A evening with unreleased song premieres.',
      ticketUrl: 'https://tickets.example.com/zoha-nyc',
      status: 'UPCOMING',
      published: true,
      image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    },
    {
      id: 'ev-3',
      title: 'Electric Odyssey Festival Headline',
      date: '2026-12-31',
      time: '22:00',
      location: 'London, UK',
      venue: 'O2 Forum Kentish Town',
      description: 'New Year Eve countdown with special guest vocalists and pyrotechnic visual accompaniment.',
      ticketUrl: 'https://tickets.example.com/zoha-london',
      status: 'UPCOMING',
      published: true,
      image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    },
  ],
  featured: {
    songId: 'song-1',
    videoId: 'vid-1',
    photoId: 'gal-1',
    storyId: 'story-1',
  },
  guestbook: [
    {
      id: 'gb-1',
      name: 'Maya Lin',
      message: 'Your guitar tone in Midnight Resonance literally brought tears to my eyes. Cannot wait for the live tour!',
      createdAt: '2026-08-10T14:22:00Z',
      status: 'approved',
    },
    {
      id: 'gb-2',
      name: 'David K.',
      message: 'The YouTube tutorials and behind-the-scenes vlogs inspired me to pick up the guitar again after 6 years.',
      createdAt: '2026-08-15T09:10:00Z',
      status: 'approved',
    },
    {
      id: 'gb-3',
      name: 'Elena Rostova',
      message: 'ZOHA 2.0 is the most stunning artist experience on the web. Pure cinema!',
      createdAt: '2026-08-20T19:45:00Z',
      status: 'approved',
    },
  ],
  contactMessages: [
    {
      id: 'msg-1',
      name: 'Universal Sound Festival',
      email: 'booking@universalsound.org',
      subject: 'Headline Booking Inquiry 2027',
      message: 'We would love to invite ZOHA to headline our Main Stage in August 2027. Please let us know your availability.',
      createdAt: '2026-08-25T11:00:00Z',
      read: false,
      archived: false,
    },
  ],
  pressKit: {
    biography: 'ZOHA is a genre-defying music artist, singer, and guitarist known for fusing cinematic strings with atmospheric electronica. With over 100,000 worldwide streams and captivating YouTube performance visuals, ZOHA has established a singular aesthetic world that connects acoustic intimacy with arena-scale power.',
    downloadableProfileUrl: 'https://zoha-artist.example.com/press-kit.pdf',
    hiResPhotos: [
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1920&q=90',
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1920&q=90',
      'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1920&q=90',
    ],
    stageRiderUrl: 'https://zoha-artist.example.com/stage-rider-2026.pdf',
    contactEmail: 'contact@zoha.com',
    bookingPhone: '+1 (555) 019-ZOHA',
    pressQuotes: [
      {
        quote: 'An astonishing fusion of acoustic virtuosity and cinematic grandeur.',
        source: 'Rolling Sound Magazine',
      },
      {
        quote: 'ZOHA crafts soundscapes that linger long after the final chord fades.',
        source: 'Acoustic & Vision Daily',
      },
    ],
  },
  settings: {
    siteTitle: 'ZOHA 2.0 — Official Artist & Creative Platform',
    artistName: 'ZOHA',
    tagline: 'Music • Stories • Visuals',
    themePreset: 'MIDNIGHT_GOLD',
    accentColor: '#F59E0B',
    contactEmail: 'zoharoza587@gmail.com',
    socialLinks: {
      youtube: 'https://youtube.com/@zoha-music',
      instagram: 'https://instagram.com/zoha.music',
      facebook: 'https://facebook.com/zoha.official',
      tiktok: 'https://tiktok.com/@zoha.music',
      spotify: 'https://spotify.com/artist/zoha',
      soundcloud: 'https://soundcloud.com/zoha-sound',
    },
    customCursorEnabled: true,
    ambientSoundEnabled: true,
    seo: {
      metaTitle: 'ZOHA 2.0 | Official Artist, Music & Creative Platform',
      metaDescription: 'Step into the official creative world of ZOHA. Stream original songs, watch exclusive YouTube videos, explore photography, and experience cinematic storytelling.',
      ogImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=85',
      keywords: 'ZOHA, ZOHA 2.0, artist, singer, guitarist, acoustic guitar, indie music, YouTube covers, cinematic music, live concert',
    },
  },
  analytics: {
    pageViews: 18450,
    videoOpens: 6240,
    galleryOpens: 4910,
    musicPlays: 12890,
    guestbookEntries: 48,
    moodSelections: {
      CALM: 420,
      NOSTALGIC: 380,
      DREAMY: 510,
      ENERGETIC: 290,
      MELANCHOLIC: 340,
      ACOUSTIC: 620,
    },
    recentActivities: [
      { id: 'act-1', action: 'Video "Midnight Resonance" viewed', timestamp: '2 minutes ago' },
      { id: 'act-2', action: 'Track "Midnight Resonance" played', timestamp: '7 minutes ago' },
      { id: 'act-3', action: 'New guestbook message submitted', timestamp: '24 minutes ago' },
      { id: 'act-4', action: 'Gallery lightbox opened: The Electric Silhouette', timestamp: '1 hour ago' },
    ],
  },
};

export function getDatabase(): DatabaseSchema {
  try {
    if (!fs.existsSync(path.dirname(DB_FILE_PATH))) {
      fs.mkdirSync(path.dirname(DB_FILE_PATH), { recursive: true });
    }

    if (fs.existsSync(DB_FILE_PATH)) {
      const raw = fs.readFileSync(DB_FILE_PATH, 'utf-8');
      return JSON.parse(raw);
    }
  } catch (err) {
    console.error('Error reading database file, using default seed:', err);
  }

  saveDatabase(INITIAL_DATABASE);
  return INITIAL_DATABASE;
}

export function saveDatabase(data: DatabaseSchema): boolean {
  try {
    if (!fs.existsSync(path.dirname(DB_FILE_PATH))) {
      fs.mkdirSync(path.dirname(DB_FILE_PATH), { recursive: true });
    }
    fs.writeFileSync(DB_FILE_PATH, JSON.stringify(data, null, 2), 'utf-8');
    return true;
  } catch (err) {
    console.error('Error writing database file:', err);
    return false;
  }
}
